language: "generic"
os: "osx"
osx_image: "xcode6.4"
sudo: false
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p ~/install
install:
  - conda build recipe

